### ISSUE TITLE
Just curious how you're deploying next.js app?

### ISSUE THREAD

**Issue by twigs67** [tudorconstantin/knests#278]
Hey,

Just looking over your code and I'm wondering how you're serving the next.js app. I don't see a next.js module under `server` directory, so I'm wondering if you're even using SSR. 

I'm guessing you're serving it SSR through ZEIT and you're using nest.js as an API server or graphql in this case. If this is true, it would mean your next.js server has to request data from the API server each time a request is made? Is this right? 

Thanks

**Comment by tudorconstantin** [comment]
Hey,

I choose to use Next.JS on the frontend **not for its SSR capabilities**, but because it already has a router configured, because it offers out-of-the box a way to organize the components and pages and I think there were a few other reasons which I don't remember right now.

So, to answer your question, the _client_ is deployed as a usual browser-rendered UI app: when deployed to production, it is  served by nginx as static assets. 

And yes, in its current form, the react app should make a roundtrip to the server for info. Although, I think it's possible to have json files served statically by nginx and `require`d by your UI.

**Comment by twigs67** [comment]
@tudorconstantin thanks for the quick response.
